name: signal_store
description: A starting point for Dart libraries or applications.
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  item_store:
    git:
      url: https://github.com/krisztian2545/item_store
      ref: new-syntax
  signals_core: ^5.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
