name: signal_store_flutter
description: "A new Flutter package project."
version: 0.4.0
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  item_store_flutter:
    git:
      url: https://github.com/krisztian2545/item_store
      path: packages/item_store_flutter
  signal_store:
    git:
      url: https://github.com/krisztian2545/item_store
      path: packages/signal_store
  signals_flutter: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter: